### ISSUE TITLE
启动时会访问raw.githubusercontent.com

### ISSUE THREAD

**Issue by GGACHA** [EhViewer-NekoInverter/EhViewer#29]
### 复现步骤 / Step to reproduce

~~1.打开设置-高级-内置hosts~~
启动EhViewer

### 预期行为 / Expected behaviour

~~不访问raw.githubusercontent.com的ip, 151.101.0.133, 151.101.64.133等~~
不访问raw.githubusercontent.com
### 实际行为 / Actual Behaviour

~~访问raw.githubusercontent.com的ip, 151.101.0.133, 151.101.64.133等~~
访问raw.githubusercontent.com
### 备注 / Addition details

~~用于远程下载hosts?~~
用于远程下载什么的? 可以去除吗?

### EhViewer 版本号 / EhViewer version code

eh-1.7.28.x

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/EhViewer-NekoInverter/EhViewer/actions/runs/4022112852

### Android 系统版本 / Android version

MIUI 11

### 设备型号 / Device model

Xiaomi 12

### SoC 型号 / Soc model

晓龙8+

### 应用日志 / App logs

无

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml?query=branch%3Aeh-1.7.28.x) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml?query=branch%3Aeh-1.7.28.x)

**Comment by xb2016** [comment]
不能
