### ISSUE TITLE
显示错误

### ISSUE THREAD

**Issue by qingyaxveji** [EhViewer-NekoInverter/EhViewer#30]
### 复现步骤 / Step to reproduce

进去就看的到

### 预期行为 / Expected behaviour

当标题两行的时候，评分，星星那一行会与上传者id重合

### 实际行为 / Actual Behaviour

![Screenshot_2023-02-17-11-36-20-35_7aa5bbc6fed013f5ecb86e3306cf2065](https://user-images.githubusercontent.com/38754068/219543278-8f205b4a-fbbb-4dda-8072-ec3001d7b650.jpg)

### EhViewer 版本号 / EhViewer version code

1.27.8.7

### EhViewer CI 版本 / EhViewer CI Version

https://github.com/EhViewer-NekoInverter/EhViewer/releases

### Android 系统版本 / Android version

colorOS 13.0

### 设备型号 / Device model

一加ace2

### SoC 型号 / Soc model

骁龙8+gen1

### 应用日志 / App logs

[log-2023-02-17-11-40-58-075.zip](https://github.com/EhViewer-NekoInverter/EhViewer/files/10762965/log-2023-02-17-11-40-58-075.zip)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml?query=branch%3Aeh-1.7.28.x) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml?query=branch%3Aeh-1.7.28.x)

**Comment by qingyaxveji** [comment]
不止这个版本，1.27.8.final版也一样，我是那个版本出bug了回退到1.27.8.7发现还是这样，不知道是手机的问题还是什么

**Comment by qingyaxveji** [comment]
不过不影响使用，我就说一声

**Comment by qingyaxveji** [comment]
啊，第一次用github不知道什么是ci版，不过刚才下了ci版，第一个压缩包，重装了一下，还是这样

**Comment by qingyaxveji** [comment]
这个是新日志
[log-2023-02-17-11-56-32-153.zip](https://github.com/EhViewer-NekoInverter/EhViewer/files/10763088/log-2023-02-17-11-56-32-153.zip)

**Comment by xb2016** [comment]
所以你打的第一个勾真的看了吗？

**Comment by qingyaxveji** [comment]
> 所以你打的第一个勾真的看了吗？

啊，不好意思，漏看那一行了，我就看到不许提和内容无关的问题，抱歉抱歉

**Comment by qingyaxveji** [comment]
> 所以你打的第一个勾真的看了吗？

那行好窄，没注意，没看到，对不起

**Comment by qingyaxveji** [comment]
大小调到48就好了，谢谢你
