### ISSUE TITLE
一旦勾選「記住常用收藏」後，便無法離開此狀態（無法變回每次詢問）

### ISSUE THREAD

**Issue by ximellon** [EhViewer-NekoInverter/EhViewer#31]
### 复现步骤 / Step to reproduce

1. 將任一畫廊加入收藏時，勾選「記住常用收藏」
2. 點擊進入畫廊詳情
3. 點擊收藏（愛心），取消收藏
4. 長按收藏強制觸發收藏選單，這次不勾選「記住常用收藏」
5. 完成加入流程後，再次嘗試任一非強制觸發收藏選單的加入收藏流程

### 预期行为 / Expected behaviour

以前在上述的 4 以後，就可以變回每次詢問的行為模式，但現在並沒有辦法。

### 实际行为 / Actual Behaviour

現在的狀況是：依舊維持「記住常用收藏」的狀態，不管從外面長按呼出選單後加入，或在裡頭（詳情）直接點擊愛心，都還是會直接加入前一次記住時的收藏夾。

### 备注 / Addition details

跟崩潰無關、且看 commit 沒有修正此類問題，就不測 CI 和附上 log 了。

我大致上看了一下，問題應該是出在

app/src/main/java/com/hippo/ehviewer/ui/CommonOperations.java

L113 部分的流程沒有被正常觸發而導致此結果（不熟 Android app 不確定是不是流程被後頭增加備註的部分 (L79 附近) 給跳過了）

---

我個人是覺得以前的流程也挺詭異的，看你如何改方便，在設定多加一個「預設收藏」之類的選項也是可以接受的（吧？）

### EhViewer 版本号 / EhViewer version code

1.7.28.7

### EhViewer CI 版本 / EhViewer CI Version

N/A

### Android 系统版本 / Android version

One UI 3.1/Android 11

### 设备型号 / Device model

Galaxy Tab A 8.0 with S Pen (SM-P200)

### SoC 型号 / Soc model

Exynos 7904

### 应用日志 / App logs

N/A

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml?query=branch%3Aeh-1.7.28.x) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml?query=branch%3Aeh-1.7.28.x)

**Comment by xb2016** [comment]
以及正确做法
![image](https://user-images.githubusercontent.com/31783875/221346150-c44d17f2-fbe7-4e4a-827c-1d1bbc54e3d9.png)

**Comment by ximellon** [comment]
我剛剛試了，確實可以。原來的 app 就有這個東西嗎？看來之前我用的是奇怪的方法。 =P

**Comment by xb2016** [comment]
一直都有

**Comment by ximellon** [comment]
https://github.com/EhViewer-NekoInverter/EhViewer/commit/867bf43c68cc455a2e8311fd13f5f1a0c24b8e00

找到了，原來長按改收藏是上個作者加進去的，我沒用過最早的，所以一直都是這樣操作。 xD

剛才看不懂的 select 也是這裡加進去的。 OTL
