### ISSUE TITLE
重新下载时无法获取原来的文件

### ISSUE THREAD

**Issue by dairidong** [EhViewer-NekoInverter/EhViewer#35]
### 复现步骤 / Steps to reproduce

1. 下载一本标题为日文的画廊
2. 原标题更新为英语文本
3. 删除本子，不勾选同时删除图片文件
4. 重新下载，会重下文件，原来的文件不会被读取

### 预期行为 / Expected behaviour

直接获取原来的下载文件

### 实际行为 / Actual behaviour

重新下载，下载目录存在两份该画廊编号相同、标题不同的目录

### 备注 / Additional details

![4L`{{IBI~6$NBOQ51{QN5VD](https://user-images.githubusercontent.com/48778797/228789673-066f446c-a7f1-4d00-8ad7-7e3ccb45864f.png)

### EhViewer 版本号 / EhViewer version code

1.7.29.2

### EhViewer CI 版本 / EhViewer CI version

https://github.com/EhViewer-NekoInverter/EhViewer/actions/runs/4519769361

### Android 系统版本 / Android version

ColorOS 13 / Android 13

### 设备型号 / Device model

Oppo Find X3

### SoC 型号 / SoC model

骁龙870

### 应用日志 / App logs

无

### 自查步骤 / Self-review steps

- [ ] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by xb2016** [comment]
这是预期行为，由于 Ehviewer-Overhauled/Ehviewer#381 ，软件不会再遍历已有的文件
作为替代方案，你可以使用 **设置-下载-恢复下载项** 来恢复已删除但保留文件的下载项目

**Comment by xb2016** [comment]
> 这不算预期行为吧，不选删除文件不会从数据库删下载目录的

对哦 那这就神奇了

**Comment by xb2016** [comment]
哦 我大概知道了 下载的时候没去读已有数据 直接生成新的了
