### ISSUE TITLE
模拟器安装问题

### ISSUE THREAD

**Issue by NightSharp** [EhViewer-NekoInverter/EhViewer#36]
### 复现步骤 / Steps to reproduce

1. 下载[蓝叠Android 11 Beta版](https://www.bluestacks.com/download.html)
2. 将universal安装包拖入其中

### 预期行为 / Expected behaviour

正常安装，像彩E一样

### 实际行为 / Actual behaviour

提示无法安装如下图所示
![图片](https://user-images.githubusercontent.com/9748063/230367004-cbba2a0c-8700-4030-b45d-bc0e30dfe8a5.png)

### EhViewer 版本号 / EhViewer version code

1.7.29.3

### EhViewer CI 版本 / EhViewer CI version

https://github.com/EhViewer-NekoInverter/EhViewer/actions/runs/4626334444

### Android 系统版本 / Android version

BlueStacks 5.11.41.1005 Android 11

### 设备型号 / Device model

PC端蓝叠模拟器

### SoC 型号 / SoC model

锐龙 5800H

### 应用日志 / App logs

没有日志记录

### 自查步骤 / Self-review steps

- [ ] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by xb2016** [comment]
![image](https://user-images.githubusercontent.com/31783875/230404621-e5340a79-82fd-4cef-bf14-463cce7ce23c.png)

无法复现，并且不会考虑模拟器兼容问题
