### ISSUE TITLE
缩略图经常加载不出来，刷新几下才行（这个项目咋这么冷清啊哈哈

### ISSUE THREAD

**Issue by sash78** [EhViewer-NekoInverter/EhViewer#51]
### 复现步骤 / Steps to reproduce

1

### 预期行为 / Expected behaviour

1

### 实际行为 / Actual behaviour

1

### 备注 / Additional details

1

### EhViewer 版本号 / EhViewer version code

1.7.28

### EhViewer CI 版本 / EhViewer CI version

1

### Android 系统版本 / Android version

1

### 设备型号 / Device model

1

### SoC 型号 / SoC model

1

### 应用日志 / App logs

1

### 自查步骤 / Self-review steps

- [ ] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by xb2016** [comment]
是这样的
