### ISSUE TITLE
下载异常

### ISSUE THREAD

**Issue by Moe-hayate** [EhViewer-NekoInverter/EhViewer#53]
### 复现步骤 / Steps to reproduce

页面浏览异常，下载一直无速度

### 预期行为 / Expected behaviour

页面浏览异常，下载一直无速度

### 实际行为 / Actual behaviour

页面浏览异常，下载一直无速度
![Screenshot_2023-10-29-01-04-41-417_org moedog ehv](https://github.com/EhViewer-NekoInverter/EhViewer/assets/117423750/ce568356-3989-45fd-866c-269efb9af02a)
![Screenshot_2023-10-29-01-04-29-579_org moedog ehv](https://github.com/EhViewer-NekoInverter/EhViewer/assets/117423750/9c1266d2-953e-4f2d-9a9f-9e753bfa06fb)

### EhViewer 版本号 / EhViewer version code

1.8.1

### EhViewer CI 版本 / EhViewer CI version

377

### Android 系统版本 / Android version

MIUI 14.0.19

### 设备型号 / Device model

XIAOMI 13 U

### SoC 型号 / SoC model

骁龙8

### 应用日志 / App logs

[log-2023-10-29-00-51-42-778.zip](https://github.com/EhViewer-NekoInverter/EhViewer/files/13196396/log-2023-10-29-00-51-42-778.zip)

### 自查步骤 / Self-review steps

- [X] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by xb2016** [comment]
网络问题 超时
