### ISSUE TITLE
下载标签无法调整顺序、乱序的问题，可能与不正确的退出应用方式有关

### ISSUE THREAD

**Issue by Marsblast** [EhViewer-NekoInverter/EhViewer#56]
### 复现步骤 / Steps to reproduce

1.设置一定量的下载标签(20+)与下载画廊(1000+)后，拖动标签顺序开始出现乱序问题
2.查看Q&A，尝试清除应用数据与重装软件两种方式，且不导入数据后，重复步骤1，仍然出现同样问题
3. 发现只要通过后台关闭软件，标签便会乱序，而通过返回键退出软件则不会乱序
4. 调整下载标签顺序并通过返回键退出软件后，再次打开软件并通过后台关闭的方式关闭软件，再次启动后仍会乱序

### 预期行为 / Expected behaviour

下载标签的顺序在进行调整后不会乱序

### 实际行为 / Actual behaviour

只要通过在主界面双击返回键退出应用以外的方式使应用被关闭（如后台强制关闭、被系统自动清理、未关闭应用重启手机等），则会出现下载标签乱序情况，即使在这之前已经调整过顺序且通过双击返回正常退出重进确认标签未变动

### EhViewer 版本号 / EhViewer version code

1.8.2

### EhViewer CI 版本 / EhViewer CI version

https://github.com/EhViewer-NekoInverter/EhViewer/actions/runs/6721467135

### Android 系统版本 / Android version

Android13. ColorOS13.1

### 设备型号 / Device model

OPPO FIndX3Pro

### SoC 型号 / SoC model

骁龙888

### 应用日志 / App logs

[https://github.com/Marsblast/-E-/blob/main/logcat-2023-11-04-08-37-40-060.txt](url)

### 自查步骤 / Self-review steps

- [ ] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by xb2016** [comment]
麻烦再提供以下信息：
1. 获得该数据库所使用的软件版本？
2. 请提供导入到本软件的数据库原文件
3. 请提供出现顺序混乱的情况后 从本软件导出的数据库文件
考虑到隐私问题，文件可以通过 TG @xb2016 或邮件 web#service.moedog.org (#换@) 发送

**Comment by Marsblast** [comment]
> 麻烦再提供以下信息：
> 
> 1. 获得该数据库所使用的软件版本？
> 2. 请提供导入到本软件的数据库原文件
> 3. 请提供出现顺序混乱的情况后 从本软件导出的数据库文件
>    考虑到隐私问题，文件可以通过 TG @xb2016 或邮件 web#service.moedog.org (#换@) 发送

1.软件版本是github上发布的最新版本，即为1.8.2(be3175c)
2.由于看过QA之后我以为是因为通过导入彩E数据而导致的顺序错乱，所以我在清除软件数据后没有导入数据，而是重新下载和设置标签的
3.你需要的文件是指db文件对吗？
如果是的话，可以查看这里[https://github.com/Marsblast/-E-](url)，我把它上传了

**Comment by xb2016** [comment]
> 如果是的话，可以查看这里[https://github.com/Marsblast/-E-](url)，我把它上传了

并没有上传成功。我需要两个文件，彩E导出的文件，和出现错乱后新导出的文件

**Comment by Marsblast** [comment]
> > 如果是的话，可以查看这里[https://github.com/Marsblast/-E-](url)，我把它上传了
> 
> 并没有上传成功。我需要两个文件，彩E导出的文件，和出现错乱后新导出的文件

抱歉，我还不太会使用github，我用微软OD网盘上传了文件，可以麻烦你下载一下吗？里面有彩E的文件、白E乱序后的文件以及演示视频
https://1drv.ms/u/s!AvQzCezREeyqjxfMM8u172VZ3bC8?e=fZ2odr

**Comment by xb2016** [comment]
我看了下 彩E 和本软件的数据库结构是不一样的，请问您是如何导入成功的？
您提供的两个数据库文件的数据量也并不相同

**Comment by Marsblast** [comment]
> 我看了下 彩E 和本软件的数据库结构是不一样的，请问您是如何导入成功的？ 您提供的两个数据库文件的数据量也并不相同

我上面已经提到了我没有把彩E的数据导入进白E，因为彩E最新版本(foobar版)的数据根本不能正确导入进其它任何版本的Ehviewer，包括旧版的彩E
并且由于Q&A中您提到“数据库：转到 设置-高级-导入数据，导入您备份的数据库文件，如果应用内已存在数据，可能导致导入不完全、无法调整下载标签顺序等问题”。所以我就没有进行数据导入，而是清除了白E的数据之后直接重新下载画廊和添加下载标签的

所以这个下载标签的顺序错乱和数据导入应该是无关的？

**Comment by xb2016** [comment]
请尝试使用最新 CI 版本，此问题应已修复

但我仍需要确认一下，当前本软件内的**所有**数据都是在本软件内手动创建的？没有导入过其他任何数据？

因为导出的文件内存在理论上手动创建标签不会出现的情况

**Comment by Marsblast** [comment]
> 请尝试使用最新 CI 版本，此问题应已修复
> 
> 但我仍需要确认一下，当前本软件内的**所有**数据都是在本软件内手动创建的？没有导入过其他任何数据？
> 
> 因为导出的文件内存在理论上手动创建标签不会出现的情况

所有数据的话我不确定，因为我的手机之前是装过白E的，所以可能是在下载路径的目录里有一些残余数据？
但是我在自认为是彩E数据导入的问题之后先通过系统设置清除了白E的所有数据，然后又删除重装了一次
但我确定出现这个问题以及后面复现问题的时候是绝对没导入过其他任何ehv的数据的

因为出现这问题后我第一时间就怀疑是不是彩E数据问题，因为彩E数据导过来大部分标签都消失了，画廊消失了一千多个，更别提乱序了
然后来看了下Q&A，当时确认肯定是彩E数据有问题，然后就在系统设置里清除白E所有数据之后重新一个个创建标签，和去彩E收藏已下载画廊再到白E这下载……
结果还是有这问题，去TG和魂+上搜了搜发现好像没人说这个事儿，看到有人提到过有的bug跟可能后台杀软件有关，就在想这个会不会也是这个原因，尝试了一下发现还真是只要后台关闭软件就会标签乱序，然后就来发Issues了
（顺带一提更新后不会出现这个bug了，但是我在更新时没有双击返回退出白E结果更新软件的强制关闭也让下载标签又乱了最后一次XD）

**另外很抱歉虽然一个Issues不能提两个问题，但我还是想问下在软件内的“EHentai设置”内更改了图片分辨率为1280x，但偶尔它会自动变为Auto，这个我实在不知道是因为什么了，完全不知道是什么时候自动改的也没法复现……**

总之感谢大佬的超高速修复，非常感谢您！！！

**Comment by xb2016** [comment]
> 在软件内的“EHentai设置”内更改了图片分辨率为1280x，但偶尔它会自动变为Auto

FooIbar/EhViewer#137

E站的问题 等网站修复 与软件无关

**Comment by Marsblast** [comment]
> > 在软件内的“EHentai设置”内更改了图片分辨率为1280x，但偶尔它会自动变为Auto
> 
> [FooIbar/EhViewer#137](https://github.com/FooIbar/EhViewer/issues/137)
> 
> E站的问题 等网站修复 与软件无关

好的，感谢大佬回复，祝你生活愉快 :)
