### ISSUE TITLE
更改为显示日文标题后，部分情况下，已下载的本子名显示问题

### ISSUE THREAD

**Issue by dadi0126** [EhViewer-NekoInverter/EhViewer#57]
### 复现步骤 / Steps to reproduce

1.将ehentai账户设置为默认显示日文标题后，已经可以正常在搜索列表中显示日文标题
2.在搜索列表的结果中长按目标画廊，点击下载，下载结果中画廊名字显示日文标题
3.点击目标画廊进入详情页面后，点击该页面的下载按钮，下载结果中画廊名字为英文标题

### 预期行为 / Expected behaviour

他应该在两种情况下都将下载文件显示为日文标题

### 实际行为 / Actual behaviour

但是在操作3中，下载下来的画廊却显示为英文标题

### 应用日志 / App logs

#
[log-2024-02-05-23-22-21-329.zip](https://github.com/EhViewer-NekoInverter/EhViewer/files/14167670/log-2024-02-05-23-22-21-329.zip)

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.8.2.1(c546d78)

### EhViewer CI 版本 / EhViewer CI version

https://github.com/EhViewer-NekoInverter

### Android 系统版本 / Android version

MIUI 13.0.23

### 设备型号 / Device model

Redmi K50

### SoC 型号 / SoC model

天玑 8100

### 自查步骤 / Self-review steps

- [ ] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by xb2016** [comment]
app设置里开显示日文标题
