### ISSUE TITLE
下载标题包含特殊符号的画廊会立即闪退

### ISSUE THREAD

**Issue by M3GCh1na** [EhViewer-NekoInverter/EhViewer#58]
### 复现步骤 / Steps to reproduce

1.下载一个标题包含特殊符号（如emoji）的画廊
例如：https://exhentai.org/g/2876455/172c07826d/
2.应用会闪退，并且每次打开时点击开始下载，下载到该画廊时都会导致闪退

### 预期行为 / Expected behaviour

在其他版本的EH中，尝试下载包含emoji的画廊会显示下载失败（一直显示未启动），因为是不合法的文件夹名称，如果能做到自动忽略特殊符号就好了

### 实际行为 / Actual behaviour

它闪退了

### 应用日志 / App logs

[log-2024-04-02-17-49-36-264.zip](https://github.com/EhViewer-NekoInverter/EhViewer/files/14834713/log-2024-04-02-17-49-36-264.zip)

### 备注 / Additional details

这个问题好像是从某次更新后才出现的，之前没有遇见过

### 浏览站点 / Browsing site

ExHentai

### EhViewer 版本号 / EhViewer version code

1.8.5(b4fb2e1)

### EhViewer CI 版本 / EhViewer CI version

https://github.com/EhViewer-NekoInverter/EhViewer/actions/runs/8421950485

### Android 系统版本 / Android version

EMUI10.1.0/Android10

### 设备型号 / Device model

荣耀9X

### SoC 型号 / SoC model

Huawei Kirin 810

### 自查步骤 / Self-review steps

- [ ] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by xb2016** [comment]
请将 SD 卡格式化为 exFAT 等现代化文件系统

**Comment by M3GCh1na** [comment]
> 请将 SD 卡格式化为 exFAT 等现代化文件系统

已确认SD卡一直是exFAT格式

**Comment by M3GCh1na** [comment]
> 请将 SD 卡格式化为 exFAT 等现代化文件系统

已确认SD卡一直是exFAT格式
![-72ef13f9b137bd78](https://github.com/EhViewer-NekoInverter/EhViewer/assets/148378837/b4699d36-42cc-42b3-a9f6-ed9bd718055c)
