### ISSUE TITLE
Remote favorites category name is not displayed

### ISSUE THREAD

**Issue by soredake** [EhViewer-NekoInverter/EhViewer#59]
### 复现步骤 / Steps to reproduce

1. Install latest version.
2. Login to e-hentai.
3. Go to any manga.
4. Press on favorite button.
5. Favorite names are not displayed (only generic Favorite 1/2/3)

### 预期行为 / Expected behaviour

Another app, [eros-fe](https://github.com/3003h/Eros-FE) correctly displays names of the favorite categories:
![image](https://github.com/EhViewer-NekoInverter/EhViewer/assets/5204968/da8e2d0b-1f8e-4ea0-8362-8cc8786adf96)

### 实际行为 / Actual behaviour

No favorite category names are displayed:
![image](https://github.com/EhViewer-NekoInverter/EhViewer/assets/5204968/5c304a27-44b8-4dd3-a1b4-a2471db3ef04)

### 应用日志 / App logs

[log-2024-04-27-20-06-22-871.zip](https://github.com/EhViewer-NekoInverter/EhViewer/files/15139073/log-2024-04-27-20-06-22-871.zip)

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

1.8.5

### EhViewer CI 版本 / EhViewer CI version

https://github.com/EhViewer-NekoInverter/EhViewer/actions/runs/8782876934

### Android 系统版本 / Android version

Android 13

### 设备型号 / Device model

Moto Edge 40

### SoC 型号 / SoC model

Dimensity

### 自查步骤 / Self-review steps

- [ ] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by xb2016** [comment]
@soredake Visit once: Sidebar -> Favorites

**Comment by soredake** [comment]
@xb2016 thank you! But, can they be loaded by default, without going once to favorites tab?
