### ISSUE TITLE
Reading the gallery is consuming the image limit quickly 

### ISSUE THREAD

**Issue by TheKoakuma** [EhViewer-NekoInverter/EhViewer#60]
### 复现步骤 / Steps to reproduce

1. Open the app
2. Go to Settings > EH and take note of Image Limits value
3. Go to a non-previously read gallery
4. Read the gallery
5. Head back to Setting > EH and check the value again

### 预期行为 / Expected behaviour

The value should increase only by the pages read/loaded or so (in my tests I ran a 20 page gallery).

### 实际行为 / Actual behaviour

The value goes way higher than the read (something near 140 for a 10~20 page gallery). This leads to limit being exceeded earlier.

### 应用日志 / App logs

[log-2024-04-27-16-21-59-945.zip](https://github.com/EhViewer-NekoInverter/EhViewer/files/15139572/log-2024-04-27-16-21-59-945.zip)

### 备注 / Additional details

It may be a concurrent download issue or immediate retry, but i cant precisely tell.

### 浏览站点 / Browsing site

Both E-Hentai and ExHentai

### EhViewer 版本号 / EhViewer version code

1.8.5

### EhViewer CI 版本 / EhViewer CI version

https://github.com/EhViewer-NekoInverter/EhViewer/actions/runs/8782876934

### Android 系统版本 / Android version

MIUI Global 14.0.6.0 Android 13 TP1A.220624.014

### 设备型号 / Device model

Redmi Note 10 5G

### SoC 型号 / SoC model

Mediatek Dimensity 700 5G

### 自查步骤 / Self-review steps

- [ ] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by xb2016** [comment]
@TheKoakuma Load original image enabled?

**Comment by TheKoakuma** [comment]
Yes, Prefer Original Images is enabled on EH > EHentai Settings

**Comment by xb2016** [comment]
So no problem
