### ISSUE TITLE
1.8.1下载闪退，1.8.7下载速度0

### ISSUE THREAD

**Issue by FrancoZ18132** [EhViewer-NekoInverter/EhViewer#67]
### 复现步骤 / Steps to reproduce

昨天晚上下载本子闪退
然后去更新版本后
去下载本子速度变成了0
实际点进去看图片是没有问题的

### 预期行为 / Expected behaviour

正常来讲不应该闪退和速度0的

### 实际行为 / Actual behaviour

![Screenshot_2024-10-05-11-49-40-636_org moedog ehviewer](https://github.com/user-attachments/assets/55cd4a75-5b67-4f97-bade-17b2e439219f)

### 应用日志 / App logs

[log-2024-10-05-11-23-02-819.zip](https://github.com/user-attachments/files/17265713/log-2024-10-05-11-23-02-819.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

之前是1.8.1，现在是1.8.7

### EhViewer CI 版本 / EhViewer CI version

https://github.com/EhViewer-NekoInverter/EhViewer/releases/download/v1.8.7/EhViewer-NekoInverter-v1.8.7-universal.apk

### Android 系统版本 / Android version

miui 13.0.8  11 rkq1.211001.001

### 设备型号 / Device model

redmi note11 pro 5g

### SoC 型号 / SoC model

骁龙695 5g

### 自查步骤 / Self-review steps

- [ ] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by xb2016** [comment]
@FrancoZ18132 检查下sd卡 重设下载路径有用吗

**Comment by FrancoZ18132** [comment]
是sd卡的问题
路径换成机子里就好了
感谢
