### ISSUE TITLE
里站解析失败

### ISSUE THREAD

**Issue by RX93CN** [EhViewer-NekoInverter/EhViewer#69]
### 复现步骤 / Steps to reproduce

进入里站，打开任意一本

### 预期行为 / Expected behaviour

解析成功

### 实际行为 / Actual behaviour

列表封面显示正常，但点开任何一本都显示解析失败

### 应用日志 / App logs

> 
[log-2024-10-25-20-41-52-406.zip](https://github.com/user-attachments/files/17522246/log-2024-10-25-20-41-52-406.zip)

### 备注 / Additional details

表站无问题，赞助账号和里站账号均无法解析成功

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

1.8.7

### EhViewer CI 版本 / EhViewer CI version

https://github.com/EhViewer-NekoInverter/EhViewer/releases/tag/v1.8.7

### Android 系统版本 / Android version

android 12

### 设备型号 / Device model

xiaomi12 pro

### SoC 型号 / SoC model

骁龙8+gen1

### 自查步骤 / Self-review steps

- [X] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by xb2016** [comment]
打勾之前看了吗

**Comment by RX93CN** [comment]
抱歉，没看全



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月25日(周五) 晚上9:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [EhViewer-NekoInverter/EhViewer] 里站解析失败 (Issue #69)




 
打勾之前看了吗

**Comment by ESAKA996** [comment]
您好，我按照您的说明更新了ci版本之后还是这样，退出账号重新登录之后ex直接就是sad panda without panda了

**Comment by ESAKA996** [comment]
有类似问题的可以试着把ex设置(不是表站)里面的thumbnail settings 改成normal，gallery page thumbnail labelling 改成none，可能会解决此问题
