### ISSUE TITLE
画廊出现奇怪的错误

### ISSUE THREAD

**Issue by ESAKA996** [EhViewer-NekoInverter/EhViewer#71]
### 复现步骤 / Steps to reproduce

1.打开eh
2.进入任意画廊

### 预期行为 / Expected behaviour

应该正常显示画廊图片

### 实际行为 / Actual behaviour

实际会看到加载圈体快速旋转至满几圈然后出现红字奇怪的错误

### 应用日志 / App logs

[log-2024-10-31-15-25-13-575.zip](https://github.com/user-attachments/files/17593974/log-2024-10-31-15-25-13-575.zip)

### 浏览站点 / Browsing site

Ehentai和ex都是一样

### EhViewer 版本号 / EhViewer version code

1.8.7 cf92016

### EhViewer CI 版本 / EhViewer CI version

https://github.com/EhViewer-NekoInverter/EhViewer/actions/runs/11518214476

### Android 系统版本 / Android version

One ui 6.1, Android 14

### 设备型号 / Device model

Samsung s22 plus

### SoC 型号 / SoC model

Qualcomm Snapdragon 8 Gen 1

### 自查步骤 / Self-review steps

- [X] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by xb2016** [comment]
@ESAKA996 《您确保已使用【最新】CI 版本测试》
