### ISSUE TITLE
画廊详情页预览图最大数量高于20不响应

### ISSUE THREAD

**Issue by gwbgs** [EhViewer-NekoInverter/EhViewer#75]
### 复现步骤 / Steps to reproduce

1.设置-EH-画廊详情页预览图数量调至100
2.返回查看画廊详情页，预览图数量只有20
3.设置-EH-画廊详情页预览图数量调至14
4.返回查看画廊详情页，预览图数量为14

### 预期行为 / Expected behaviour

应该随设置改变

### 实际行为 / Actual behaviour

调至20以下时随着设置改变，调至20以上时没有改变，依然是20

### 应用日志 / App logs

[log-2024-11-25-00-20-32-097.zip](https://github.com/user-attachments/files/17894000/log-2024-11-25-00-20-32-097.zip)

### 浏览站点 / Browsing site

Exhentai

### EhViewer 版本号 / EhViewer version code

1.8.8

### EhViewer CI 版本 / EhViewer CI version

https://github.com/EhViewer-NekoInverter/EhViewer/actions/runs/11911226422

### Android 系统版本 / Android version

Xiaomi HyperOS 1.0.10.0.ULBCNXM

### 设备型号 / Device model

Xiaomi 12 pro

### SoC 型号 / SoC model

骁龙8 gen1

### 自查步骤 / Self-review steps

- [X] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by xb2016** [comment]
![image](https://github.com/user-attachments/assets/5f3c8c49-3e87-4d84-b841-71886f2e1fcf)
