### ISSUE TITLE
评分数与上传者重叠

### ISSUE THREAD

**Issue by huajideshutiao** [EhViewer-NekoInverter/EhViewer#77]
### 复现步骤 / Steps to reproduce

推测是标题有多行挤占空间
![Screenshot_2024-12-09-15-13-04-573_org moedog ehviewer-edit](https://github.com/user-attachments/assets/bbc8ebce-9063-416a-b605-1beb960087b1)

### 预期行为 / Expected behaviour

不重叠

### 实际行为 / Actual behaviour

重叠

### 应用日志 / App logs

[log-2024-12-09-15-18-35-239.zip](https://github.com/user-attachments/files/18057644/log-2024-12-09-15-18-35-239.zip)

### 浏览站点 / Browsing site

exhentai

### EhViewer 版本号 / EhViewer version code

1.8.8 (7134c09) 构建于 2024/12/02 03:07

### EhViewer CI 版本 / EhViewer CI version

https://github.com/EhViewer-NekoInverter/EhViewer/actions/runs/12111903436

### Android 系统版本 / Android version

Android 15 hyperos 2

### 设备型号 / Device model

redmi k70p

### SoC 型号 / SoC model

骁龙8g3

### 自查步骤 / Self-review steps

- [ ] 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似的问题 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml)

**Comment by ZeppLu** [comment]
我这里也有同样的问题，设置里把缩略图大小调到最大可临时解决，但代价是会很浪费屏幕空间
